### PR TITLE
Add trailing slashes to the links in the API docs nav

### PR DESCRIPTION
**Pull request by cnunciato**
While poking around doing some debugging, I happened to notice the links we're using in the API docs nav don't have trailing slashes, which causes the browser to make two requests for each click:

https://user-images.githubusercontent.com/274700/141598953-05b9a627-6282-4266-b491-4d5070036537.mov

This change should fix it up.

### CODE REVIEW

**Review by kimberleyamackenzie — COMMENTED** [review]
A couple things here:
1) The links are derived in part from the JSON.  Some of the JSON links _do_ include slashes - for example, in your demo, the `accessanalyzer` link already has a trailing slash - you can see that here in the JSON as well https://www.pulumi.com/registry/packages/navs/aws.json.  So, at the very least, we probably only want to conditionally add the slash.
2) But, I don't like the idea of having to change data in the frontend - I think we should actually update the JSON here, and either have it always include the slash or never include it, and make frontend changes to sync with whatever choice that is.

What do you think?

**Comment by cnunciato** [comment]
> I don't like the idea of having to change data in the frontend - I think we should actually update the JSON here, and either have it always include the slash or never include it, and make frontend changes to sync with whatever choice that is.

Yeah, I'm definitely with you there. @praneetloke what do you think? Would this be a straightforward change?

**Comment by praneetloke** [comment]
The package tree generator uses the same function as the docs generator to render the module link, [which appends the slash](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/package_tree.go#L45), by default. Whereas the [resource](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/package_tree.go#L60) and [function](https://github.com/pulumi/pulumi/blob/master/pkg/codegen/docs/package_tree.go#L81) links don't seem to be doing that. It looks we could safely update those functions to always suffix with a slash? It'll affect the API docs too but it seems like we would want the trailing slash to be there by default when using the module index pages to navigate as well.

**Comment by cnunciato** [comment]
Thanks @praneetloke. Yep, that's right -- we'll always want a trailing slash for these as well, since they'll be rendered as `index.html`s. I'll give that a shot, then, and close this PR. Thanks to you both!

**Pull request closed without merging**
