### PR TITLE
WIP: HTML details-based tree

### PR DESCRIPTION
**Pull request by cnunciato**
This is just me fiddling with using a [native `details` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) for the API nav tree-view control, rather than custom elements. Just wanted to see whether it was feasible and what the performance differences were. Associated docs PR (for previews) at https://github.com/pulumi/docs/pull/6760.

Also removes the dependency on @pulumi/facet (and thus Microsoft FAST), since the FAST tree view is the only component we're currently using from that library.

### CODE REVIEW

**Comment by cnunciato** [comment]
@kimberleyamackenzie Would you be up for working with me to get this over the line? I'd love to remove the transitive dep on FAST (see [this WIP PR which replaces FAST with Stencil](https://github.com/pulumi/facet/pulls) in the Facet package as well) and I think this'll land us in a better place.

**Comment by susanev** [comment]
@cnunciato we've got a pretty full plan for this iteration, and a high-priority item related to some pricing page updates, and a new marketing page. would it be alright if we consider this for the next iteration instead? is there any urgency we should be aware of?

**Comment by cnunciato** [comment]
No urgency at the moment, next iteration would be ✨. Thanks!

**Comment by cnunciato** [comment]
Hey folks -- checking in on this one. What do y'all think? Can we pick it back up soonish? It'd just be great to be able to get the FAST stuff outta there.

**Comment by susanev** [comment]
No, unfortunately not, the marketing work more than doubled which shifted a lot of things back. It's up for consideration for the next iteration.

**Comment by cnunciato** [comment]
Thank you thank you! That would be spectacular. 🙏

**Comment by cnunciato** [comment]
Checking in again on this one. Think we can do it? This change alone should reduce the size of the JS bundle by about half ('cause it jettisons FAST), so would really like to get it done. 🙏

**Comment by cnunciato** [comment]
Ok sounds good. I may go ahead and pick this up then.

**Pull request closed without merging**
