### PR TITLE
Add a secondary hero button

### PR DESCRIPTION
**Pull request by joeduffy**
In prep for some experiments we are going to run on the homepage, we'd like a button that looks like our primary hero button, but uses the same styling as our existing .btn-secondary style. This seems to do the trick!

Here's an example of it in action (the "Download" button):

image

### CODE REVIEW

**Comment by susanev** [comment]
@joeduffy this doesnt seem right, the text and the outline should be the purple color; i thought you would be able to access our secondary styles without needing any changes to this repo. @kimberleyamackenzie thoughts?

**Comment by joeduffy** [comment]
I basically copied https://github.com/pulumi/theme/blob/master/src/scss/_buttons.scss#L19-L25. The problem was the hero  button is an entirely different style, presumably because we wanted it to be "bigger"? See https://github.com/pulumi/theme/blob/master/src/scss/_hero.scss#L95-L98. That said, I am a CSS hack, and I am willing to bet 99.999% that I am wrong somehow here, and would happily take a different path. And hey, at least I got rid of the hard-coded `style="..."` that I originally used! 😆

**Comment by susanev** [comment]
theoretically, we should be able to do `btn-secondary ml-4 px-12 py-4` on your button with no changes here. but the marketing CSS overrides this, ive opened up https://github.com/pulumi/theme/pull/160 which will allow use to use ! for important until the CSS gets worked out. this will allow you to use `btn-secondary ml-4 !px-12 !py-4` in ur html.

**Comment by joeduffy** [comment]
Closing in favor of https://github.com/pulumi/theme/pull/160 -- Thanks @susanev!

**Pull request closed without merging**
