### PR TITLE
Add root name to api doc search to ensure accurate filtering

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
This fixes:
https://github.com/pulumi/registry/issues/733 

Essentially, for nav trees with a depth of 2, we were rendering matches for a search based only on parent name - which works when either the parent name is unique or the search term doesn't exist as a child of a non-unique parent, but not in cases where structure includes many parents with names like `v1` or `alpha`.  

This fix passes along the name of the root as well as the parent with any given node, and checks that both root and parent match before inserting a node into the tree of matching results.

### Verification
I have tested this on a preview built over in registry: http://registry-origin-pr-734-c767d276.s3-website.us-west-2.amazonaws.com/registry

The particular scenario outlined in the bug is fixed (see screenshots below), and I haven't seen any regressions with other random searching I've done on the AWS or AIven or Kubernetes docs.  If you could give it a spin + make sure all seems right with any weird edge case searches, that would be great!  I've filed https://github.com/pulumi/pulumi-hugo/issues/2597 for getting testing up and going in theme to catch regressions like this.

Before:
Screen Shot 2022-03-14 at 11 51 21 AM

With this change:
Screen Shot 2022-03-14 at 11 51 10 AM

### CODE REVIEW

**Review by susanev — APPROVED** [review]
thank you for fixing this so quickly!!

does this also fix https://github.com/pulumi/registry/issues/435?

**Review by cnunciato — APPROVED** [review]
LGTM, thanks for the fix. 

I'm sure you've probably done this already, but just in case, since we don't have a ton of coverage around this stuff, we should verify manually against a handful of other packages to make sure we don't regress elsewhere.

**Comment by susanev** [comment]
@kimberleyamackenzie im happy to help with manual testing if youd like, just let me know.

**Comment by kimberleyamackenzie** [comment]
@susanev just built a preview with google-native docs and it looks like this does fix 435 too.  if you have a couple minutes to poke around that link and just compare that nothing seems off about any search results compared to prod, that would be great!  i've done some manual testing with random search terms, but since there's not a ton of method to that, a second pair of eyes would be great

http://registry-origin-pr-734-9329361b.s3-website.us-west-2.amazonaws.com/registry/packages/google-native/api-docs/

Screen Shot 2022-03-14 at 1 04 31 PM

**Comment by susanev** [comment]
@kimberleyamackenzie poked a bit, not seeing any regressions, lets :shipit:

**Review by EvanBoyle — COMMENTED** [review]
@kimberleyamackenzie sorry I got here a little late. I can see how this would work for the current bug, but I think this might not quite cover all cases. For instance there could be two nodes that share the same root that have the same name:

`foo.v1.bar.v1.buzz`

We already pipe the full path in the recursive call and compute a fully qualified `nodeName`: 

https://github.com/pulumi/theme/blob/master/stencil/src/components/pulumi-api-doc-filterable-nav/pulumi-api-doc-filterable-nav.tsx#L97

I think we should be passing along this fully qualified name as a more robust identifier for comparison.

**Comment by susanev** [comment]
@EvanBoyle would you mind opening up a new issue?

**Comment by EvanBoyle** [comment]
@susanev here it is https://github.com/pulumi/registry/issues/2256

**Pull request merged**
