### PR TITLE
Add trailing slash to fix SEO errors

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
Fixes https://github.com/pulumi/registry/issues/735, which should in turn resolve many SEO temporary redirect errors.  See the preview generated [in this PR](https://github.com/pulumi/registry/pull/1792) to see the change in action - ultimately the experience should seem exactly the same as it is now, but with trailing slash on links in the API docs left nav (see examples below).

Currently in prod - no trailing slash on the nav link:
Screen Shot 2022-12-05 at 3 04 54 PM

With this change - trailing slash on the nav link:
Screen Shot 2022-12-05 at 3 04 16 PM

### CODE REVIEW

**Review by cnunciato — COMMENTED** [review]
The code _looks_ right, but on this page for example, the links in the expanded nav 404 because they get an extra slash _before_ the resource name:

http://registry-origin-pr-1792-bb4a5bab.s3-website.us-west-2.amazonaws.com/registry/packages/aws/api-docs/accessanalyzer/analyzer/

image

**Comment by kimberleyamackenzie** [comment]
@cnunciato okay, i think this should be fixed up now in the latest preview - http://registry-origin-pr-1792-85e897e5.s3-website.us-west-2.amazonaws.com/registry

**Review by cnunciato — APPROVED** [review]
LGTM! Ran a local build as well and no issues so far. 🎉

**Review by susanev — APPROVED** [review]
🌟

**Pull request merged**
