### PR TITLE
Show property-replacement icon in registry api docs

### PR DESCRIPTION
**Pull request by kimberleyamackenzie**
Adds an icon for property-replacement in Registry API docs, and handles cases for both items where there is only the replacement property as well as items that both trigger replacement and are required.  

Below is a link with a number of examples (created the Registry PR just for this preview, that does not need review/merging):
http://registry-origin-pr-1023-85042699.s3-website.us-west-2.amazonaws.com/registry/packages/snowflake/api-docs/externalfunction/

- The replacement icon should appear on items with that property
- The replacement icon should appear to the right of the required asterix on items with both 
- The tooltips for the above scenarios should behave as pictured above
- There should be no changes in behavior or visuals for items without the replacement property

Screen Shot 2022-06-02 at 11 41 11 AM
Screen Shot 2022-06-02 at 11 43 53 AM
Screen Shot 2022-06-02 at 11 45 18 AM

### CODE REVIEW

**Comment by anita-trimbur** [comment]
Would it be a huge pain to have separate tooltips in instances where both the required and replacement icons appear? I'm concerned that combining them into a single tooltip impacts clarity.

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur Also the other thing to consider is the mobile tap target for the tooltips - they will probably need a bunch more space between on mobile if they have separate tooltips, to allow individual taps.  Let me know if that sounds okay too!

**Comment by anita-trimbur** [comment]
Good callout. I find mobile tooltips to be an unideal experience in general. In this case, maybe it's possible to float the replacement icon to the right on mobile to keep them separate? Circled in yellow.

**Comment by kimberleyamackenzie** [comment]
@anita-trimbur and I chatted via DM, and I've made some updates here - distinct tooltips for each icon, and updated spacing on mobile to enable easy touch taps.  Here's the new url (also updated in description):

http://registry-origin-pr-1023-85042699.s3-website.us-west-2.amazonaws.com/registry/packages/snowflake/api-docs/externalfunction/

Screen Shot 2022-06-03 at 10 39 34 AM
Screen Shot 2022-06-03 at 11 00 59 AM
Screen Shot 2022-06-03 at 11 01 10 AM

**Review by anita-trimbur — APPROVED** [review]

**Pull request merged**
